services:
  # 1. Web Server (Nginx)
  webserver:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  # 2. PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_php
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  # 3. Database MySQL 8.3
  mysql:
    image: mysql:8.3
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # 4. phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_pma
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  # 5. File Browser (Fix Permission www-data)
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: file_manager
    user: "33:33"              # Gunakan UID/GID www-data (default PHP/Nginx)
    ports:
      - "9090:80"
    volumes:
      - ./src:/srv
      - ./filebrowser_data:/database
    environment:
      FB_BASEURL: ""           # optional
    networks:
      - app-network

# Persist DB
volumes:
  db_data:

# Network
networks:
  app-network:
    driver: bridge
