services:
  # 1. Web Server (Nginx)
  webserver:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html # Mounting source code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Config Nginx
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  # 2. PHP Application
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_php
    volumes:
      - ./src:/var/www/html # Mounting source code agar live edit
    networks:
      - app-network

  # 3. Database (MySQL 8.3)
  mysql:
    image: mysql:8.3
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql # Persistensi data database
    networks:
      - app-network

  # 4. Database Management (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_pma
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

# Setup Volume agar data DB tidak hilang saat container mati
volumes:
  db_data:

# Setup Network agar semua container bisa saling komunikasi
networks:
  app-network:
    driver: bridge